### ISSUE TITLE
Update Coastal Composite layer service url

### ISSUE THREAD

**Issue by shawnmgoulet** [capecodcommission/sea-level-rise-viewer#29]
The NOAA Coastal composite layer is not loading. It is clicking on and off and the legend is responding but no layer appears. The layer, I believe should be [this](https://www.coast.noaa.gov/arcgis/rest/services/FloodExposureMapper/CFEM_CoastalFloodHazardComposite/MapServer/12) which still looks like it is live. It might be a geojson issue?

**Comment by shawnmgoulet** [comment]
@rocketjay - [This layer](https://maps.coast.noaa.gov/arcgis/rest/services/FloodExposureMapper/CFEM_CoastalFloodHazardComposite/MapServer/12) is not able to be added as it has a null geometry type (see below). Therefore, I've added the [Map Service](https://maps.coast.noaa.gov/arcgis/rest/services/FloodExposureMapper/CFEM_CoastalFloodHazardComposite/MapServer/) Service. This works, just not exclusively a MA visualization.

![image](https://user-images.githubusercontent.com/3179974/118753614-5b53e600-b833-11eb-9f18-4de2d81e6e93.png)

**Comment by rocketjay** [comment]
Ok, we might have to watch for draw time then. The deal is its raster not vector correct?

**Comment by shawnmgoulet** [comment]
It's a cached map service, so the images that the server sends should be pretty performant.
![image](https://user-images.githubusercontent.com/3179974/118908520-93b8fa00-b8ef-11eb-8e1d-3d01f8ca91d0.png)
