### ISSUE TITLE
Change service urls

### ISSUE THREAD

**Issue by shawnmgoulet** [capecodcommission/sea-level-rise-viewer#31]
Change service urls to (just sea level rise services - roads and polygons): https://gis-test.capecodcommission.org/arcgis/rest/services/SeaLevelRise/SLR_Layers/MapServer

**Comment by shawnmgoulet** [comment]
Critical facilities' operational layer makes use of the 10.4.1's Critical Facilities service: https://gis-services.capecodcommission.org/arcgis/rest/services/Data_People/Infrastructure/MapServer/12.

@rocketjay - should this service be published to 10.8.1 as well?

**Comment by rocketjay** [comment]
It should but that might be more involved. Lets keep it to the 10.4.1 version for now. This will be something I can change in the future.
